### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by SolidZORO** [SolidZORO/leaa#13]
## **TODOS-v1**

- [ ] **leaa-api**
  - [ ] Order
  - [ ] Product
    - [ ] Specs (universal property)
  - [ ] Warehouses
  - [ ] Stocktaking
  - [ ] Statistics
  - [ ] Booking
  - [ ] Coupon
  - [ ] Promo
  - [ ] Payment
    - [ ] Alipay
    - [ ] Wechat
- [ ] **leaa-dashboard**
  - [ ] Order
  - [ ] Product
    - [ ] Specs (universal property)
  - [ ] Warehouses
  - [ ] Stocktaking
  - [ ] Statistics
  - [ ] Booking
  - [ ] Coupon
  - [ ] Promo
- [ ] **leaa-www**
  - [ ] Account
    - [ ] Login
      - [ ] Phone
    - [ ] Register
      - [ ] Phone
    - [ ] Forget Password
    - [ ] Profile
      - [ ] Upload Avatar
      - [ ] Bind / Unbind OAuth Account
  - [ ] Cart
  - [ ] Checkout
  - [ ] Payment
    - [ ] Alipay
    - [ ] Wechat
  - [ ] Order
  - [ ] Product
  - [ ] Booking
  - [ ] Coupon
  - [ ] Promo

## **TODOS-v0**

- [x] **\_leaa-common**
- [x] **leaa-api** ([demo](https://test-leaa-api.herokuapp.com)) / backend (Nest.js + TypeGraphQL + MySQL + Docker Compose)
  - [x] Auth
    - [x] Email
    - [x] Wechat
    - [x] Wechat MiniProgram
  - [x] User
  - [x] Role
  - [x] Permission
  - [x] Article
  - [x] Attachment
    - [x] Local
    - [x] OSS
    - [x] OSS sync to Local
    - [x] @2x to @1x
  - [x] Ax (Ad)
  - [x] Category (infinity level)
  - [x] Tag (word segmentation by NodeJieba)
  - [x] Logger
  - [x] Seed
  - [x] Setting
- [x] **leaa-dashboard** ([demo](https://leaa-dashboard.now.sh)) / dashboard (React.js + Antd + MobX + Apollo / GraphQL)
  - [x] Auth
  - [x] User
  - [x] Role
  - [x] Permission
  - [x] Home
  - [x] Ax (Ad)
  - [x] Category (infinity level)
  - [x] Tag (word segmentation by NodeJieba)
  - [x] Article
    - [x] WYSIWYGEditor
  - [x] Attachment
    - [x] Drop to Upload
    - [x] Drop to Sort
  - [x] Setting
  - [x] Error Boundary
  - [x] Responsive Design
  - [x] i18n
- [x] **leaa-www** ([demo](https://leaa-www.now.sh)) / website (Next.js + GraphQL)
  - [x] Home
  - [x] Account
    - [x] Login
      - [x] Email
      - [x] Wechat
    - [x] Register
      - [x] Email
      - [x] Wechat
    - [x] Logout
  - [x] Article
    - [x] List
    - [x] Item
  - [x] Banner Swiper
    - [x] Support Retina @2x
    - [x] Image Lazyload
  - [x] SEO (HtmlMeta)
- [x] **leaa-miniprogram** / wechat-miniprogram (Taro.js + GraphQL)
  - [x] Home
  - [x] Account
    - [x] Login
    - [x] Logout
  - [x] Article
    - [x] List
    - [x] Item (Rich Text)
- [x] **leaa-app** / iOS and Android (expo + GraphQL)
  - [x] Home
  - [x] Account
    - [x] Login
    - [x] Logout
  - [x] Article
    - [x] List
    - [x] Item (Webview)
